version: '3'
services:
  db:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - './database/data:/data/db'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge